[project]
name = "oauth-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.9.6",
    "dotenv>=0.9.9",
    "llama-index>=0.14.14",
    "llama-index-tools-tavily-research>=0.4.2",
    "openai>=2.21.0",
]
